### ISSUE TITLE
revoke OAuth on GitHub and stuck

### ISSUE THREAD

**Issue by rat-h** [flatironinstitute/kachery-cloud#16]
I grand access to GitHub from Kachery, but then revoked it. Now the kachery account exists, but I cannot delete it. Iit doesn't show the user name and doesn't allow me to register a new client. Could you please add a delete button on the Kachery gateway so that I can reinitialize the gateway account from scratch?

**Comment by magland** [comment]
Hi @rat-h
I am not able to reproduce the problem. I tried revoking access for my user. Then I cleared the auth token in kachery-gateway. Then I clicked to log in again, and it brought me to the github oauth page as expected.
Could you please provide some more details on what steps you took to get to the problematic state?

**Comment by rat-h** [comment]
> Then I cleared the auth token in kachery-gatewa
How? What I have is that:
![Screenshot_20230414_142357](https://user-images.githubusercontent.com/10002849/232126949-11c62b1c-9c01-4c24-9dc5-accacb8136cb.png)
![Screenshot_20230414_142430](https://user-images.githubusercontent.com/10002849/232126979-b36cb934-c407-43eb-a7e1-2cfa25e5797f.png)

I've tried to delete `~/.kachery-cloud` and re run `kachery-cloud init` with any luck

**Comment by rat-h** [comment]
Uh, I see CLEAR_ACCESS TOKEN is a button! Who can imagine!
