### ISSUE TITLE
how to load a directory?

### ISSUE THREAD

**Issue by GandalfTGrey** [flatironinstitute/kachery-cloud#6]
how can i load a directory starts with sha1dir? such likethis:  sha1dir://49b1fe491cbb4e0f90bde9cfc31b64f985870528.paired_boyden32c/1103_1_1

**Comment by jsoules** [comment]
The `sha1dir`-type links are actually from a previous version of the protocol which is no longer supported by kachery-cloud.

If you’re looking for the PAIRED_BOYDEN recordings from Spikeforest, those can be downloaded through kachery-cloud with a script like this: https://github.com/flatironinstitute/spikeforest/blob/main/examples/list_all_recordings.py

We haven’t yet transitioned all recordings to the cloud store, so if you’re looking for another spikeforest recording and can’t find it, please let us know and we’ll make it available in the new system.

**Comment by GandalfTGrey** [comment]
Thanks for replying! It sometimes cause confussion when downloading files from SpikeForest website cause it's using sha1dir URIs. Or can I use ` kachery-cloud-load ` to download them with URIs from here? https://github.com/flatironinstitute/spikeforest_recordings 
Are those URIs still work?

**Comment by GandalfTGrey** [comment]
and from this example https://github.com/flatironinstitute/spikeforest/blob/main/examples/load_extractors_for_recording.py
it shows anthor way to load spikeforest data by ` R = sf.load_spikeforest_recording(study_name='paired_boyden32c', recording_name='1103_1_1') ` ,  how many studyset can be downloaded by this way? cause i find some cannot.
